In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt


In [2]:
!pip install joblib

  Using cached joblib-1.1.0-py2.py3-none-any.whl (306 kB)


In [3]:
import joblib
plt.style.use("fivethirtyeight")

1e-4=10^-4,
eta=learning rate,
underscore is hidden method thatswhy we're using(not some protective method though)

In [29]:
class Perceptron:
    def __init__(self,eta:float=None,epochs:int=None):
        self.weights=np.random.randn(3)*1e-4
        self.eta=eta #learning rate
        self.epochs=epochs #iteration
        
    def _z_outcome(self,input,weights):
        return np.dot(input,weights)
    
    def activation_function(self,z):
        return np.where(z>0,1,0)
    
    def fit(self,X,y):
        self.X=X
        self.y=y
        
        X_with_bias=np.c_[self.X,-np.ones((len(self.X),1))]
        print(f"X with bias:\n{X_with_bias}")
        
        for epoch in range(self.epochs):
            print("- -"*10)
            z=self._z_outcome(X_with_bias,self.weights)
            y_hat=self.activation_function(z)
            
            print(f"predicted value after the forward pass:\n{y_hat}")
            
            self.error=self.y-y_hat
            print(f"error:\n{self.error}")
            
            self.weights=self.weights+self.eta * np.dot(X_with_bias.T,self.error)
            print(f"updated weights after each epoch:{epoch+1}/{self.epochs}:\n{self.weights}")
            print(f"##"*10)
            
    def predict(self,X):
        X_with_bias=np.c_[X,-np.ones(len(X),1)]
        z=self._z_outcome(X_with_bias,self.weights)
        return self.activation_function(z)

In [14]:
OR={
    "x1":[0,0,1,1],
    "x2":[0,1,0,1],
    "y":[0,1,1,1]
}
df_OR=pd.DataFrame(OR)
df_OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [15]:
def prepare_data(df,target_col="y"):
    X=df.drop(target_col,axis=1)
    y=df[target_col]
    
    return X,y



In [16]:
X,y=prepare_data(df_OR)

In [21]:
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [22]:
y

0    0
1    1
2    1
3    1
Name: y, dtype: int64

In [30]:
X,y=prepare_data(df_OR)
ETA=0.1
EPOCHS=10
model_or=Perceptron(eta=ETA,epochs=EPOCHS)
model_or.fit(X,y)


X with bias:
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
- -- -- -- -- -- -- -- -- -- -
predicted value after the forward pass:
[0 0 0 0]
error:
0    0
1    1
2    1
3    1
Name: y, dtype: int64
updated weights after each epoch:1/10:
[ 0.20001881  0.19994579 -0.29993842]
####################
- -- -- -- -- -- -- -- -- -- -
predicted value after the forward pass:
[1 1 1 1]
error:
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after each epoch:2/10:
[ 0.20001881  0.19994579 -0.19993842]
####################
- -- -- -- -- -- -- -- -- -- -
predicted value after the forward pass:
[1 1 1 1]
error:
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after each epoch:3/10:
[ 0.20001881  0.19994579 -0.09993842]
####################
- -- -- -- -- -- -- -- -- -- -
predicted value after the forward pass:
[1 1 1 1]
error:
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after each epoch:4/10:
[2.00018808e-01 1.99945786e-01 6.15814324